version: '3.9'

services:
 db:
  container_name: 
  image: cicd:latest
  restart: unless-stopped
  ports:
   - 8000:8000
  healthcheck:
   test: ["CMD-SHELL", "pg_isready -U postgres -d pythonapp_db"]
   interval: 1m30s
   timeout: 30s
   retries: 5
   start_period: 30s